# render.yaml
services:
  - type: web
    name: kindcare-platform
    env: python
    plan: free # Or 'starter' etc.
    # Command to install dependencies
    buildCommand: "pip install -r requirements.txt"
    # Command to start the application
    # Render sets the PORT environment variable, but Gunicorn defaults to 10000 if not specified.
    # Binding to 0.0.0.0 is important for Render.
    startCommand: "gunicorn --bind 0.0.0.0:10000 app:app"
    # Environment variables will be set in the Render Dashboard
    envVars:
      - key: SECRET_KEY
        sync: false # Means you will set this in the dashboard
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_PRIVATE_KEY_ID
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
      - key: FIREBASE_CLIENT_ID
        sync: false
      - key: FIREBASE_CLIENT_CERT_URL
        sync: false
      - key: FIREBASE_STORAGE_BUCKET
        sync: false
      # Optional: Set to "production" if your app checks this
      # - key: FLASK_ENV
      #   value: production